# Generated by Django 2.0.4 on 2018-04-16 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, null=True)),
                ('portrait', models.FileField(null=True, upload_to='portrait/')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, unique=True)),
                ('access', models.CharField(max_length=10)),
                ('permission', models.IntegerField(choices=[(0, 'Deny'), (1, 'View'), (2, 'Edit')])),
            ],
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, unique=True)),
                ('permissions', models.ManyToManyField(to='imbition.Permission')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='permission_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imbition.PermissionGroup'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
