# Generated by Django 2.0.4 on 2018-04-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='access',
            field=models.CharField(max_length=50),
        ),
    ]
