# Generated by Django 2.0.4 on 2018-04-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0002_auto_20180416_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='imbition.Department')),
            ],
        ),
        migrations.RemoveField(
            model_name='permissiongroup',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='permission_group',
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission',
            field=models.IntegerField(choices=[(1, 'View'), (2, 'Change'), (3, 'Add Delete')]),
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
        migrations.AddField(
            model_name='department',
            name='permissions',
            field=models.ManyToManyField(null=True, to='imbition.Permission'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(null=True, to='imbition.Department'),
        ),
    ]
