# Generated by Django 2.0.4 on 2018-04-17 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0004_auto_20180417_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='positions', to='imbition.Permission'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imbition.Position'),
        ),
    ]
