# Generated by Django 2.0.4 on 2018-04-17 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0005_auto_20180417_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessed_by', to='imbition.Position'),
        ),
    ]
