# Generated by Django 2.0.4 on 2018-04-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0006_auto_20180417_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='owned_by', to='imbition.Permission'),
        ),
    ]
