# Generated by Django 2.0.4 on 2018-04-20 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0007_auto_20180417_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
