# Generated by Django 2.0.4 on 2018-04-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0008_employee_jwt_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='jwt_secret',
        ),
    ]
