# Generated by Django 2.0.4 on 2018-04-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0010_record_recordfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='field',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='imbition.RecordField'),
            preserve_default=False,
        ),
    ]
