# Generated by Django 2.0.4 on 2018-04-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0011_record_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfield',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('field', 'date', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='recordfield',
            unique_together={('position', 'name')},
        ),
    ]
