# Generated by Django 2.0.4 on 2018-04-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0012_auto_20180429_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='sp_value',
        ),
        migrations.AddField(
            model_name='record',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
