# Generated by Django 2.0.4 on 2018-05-12 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0014_auto_20180506_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('position', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_employees', to='imbition.Position')),
            ],
        ),
    ]
