# Generated by Django 2.0.4 on 2018-05-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0017_pendingemployee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfield',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
