# Generated by Django 2.0.4 on 2018-05-22 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0020_usersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingemployee',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
