# Generated by Django 2.0.4 on 2018-05-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0022_auto_20180522_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingemployee',
            name='user',
        ),
        migrations.AlterField(
            model_name='pendingemployee',
            name='password',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
