# Generated by Django 2.0.4 on 2018-05-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0023_auto_20180524_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingemployee',
            name='username',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
