# Generated by Django 2.0.4 on 2018-05-24 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imbition', '0024_pendingemployee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingemployee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
