# Generated by Django 2.0.4 on 2018-05-25 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imbition', '0025_pendingemployee_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterObj', models.CharField(blank=True, max_length=500, null=True)),
                ('searchText', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
