# Generated by Django 2.0.4 on 2018-05-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0026_filterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterprofile',
            name='name',
            field=models.CharField(default='Test', max_length=50),
            preserve_default=False,
        ),
    ]
