# Generated by Django 2.0.4 on 2018-05-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imbition', '0027_filterprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterprofile',
            name='columnHidden',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='filterprofile',
            name='showComment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
